### ISSUE TITLE
Implement LowTicketSeller::assignSeat

### ISSUE THREAD

**Issue by flip40** [CS149-3/homework3#5]
This function needs to do the following:
-  The seating array will be a 2d array of strings called seats `this->seats`
-  The low-priced sellers assigns seats starting with row 10 (the back) and works towards the front.

Remember array values will be row # - 1

**Comment by FMock** [comment]
I'll work on this function:
Implement LowTicketSeller::assignSeat

**Comment by flip40** [comment]
By the way, there is an assignee thing over on the right, if you click the cog you can set yourself as the assignee It shows up with your symbol on the issue when view the full issues list, so that is kinda cool.

**Comment by FMock** [comment]
Oh cool! I didn't never noticed that before.
Just posted PR for this issue. I think it's completed

**Comment by flip40** [comment]
closed by #11
